server:
  port: 8070
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unwe-register?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: Aleksandar
    password:
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  expiration: 7200 #seconds
  secret: SuperSecretKey

